### ISSUE TITLE
OctoPrint-PrusaSlicerThumbnails incompatibility.

### ISSUE THREAD

**Issue by dianlight** [OctoPrint/OctoPrint-CommandSplitter#2]
Hi,
 I found that if I enable the plugins the Thumbnails generted by PrusaSlicer are modified in the gcode and OctoPrint-PrusaSlicerThumbnails go in loop. [Reference Bug#18 on PrusaSlicer](https://github.com/jneilliii/OctoPrint-PrusaSlicerThumbnails/issues/18)

**Comment by foosel** [comment]
Please provide:

  * `octoprint.log` from an upload with both plugins enabled
  * an original GCODE file with embedded thumbnail
  * the resulting GCODE file from your OctoPrint instance after upload with CommandSplitter enabled

Also why do you even have this plugin installed, it shouldn't be needed outside of very specific circumstances caused by weird slicer configurations.

As a side note, I can't see how CommandSlicer could be causing issues here, it only preprocesses files and it doesn't touch comments.

**Comment by dianlight** [comment]
Hi,
I needed it because I used the OctoKlipper plugin which had a bug on multiline gcode macros. It remained in my installation by accident now I would not need it anymore.

Below you will find all the required data. From what I have been able to analyze, the only "flaw" that can be attributed to your plugin is to remove the empty lines inside the gcode.
If you do not see the need to correct it since the resulting gcode is valid, I would advise you to insert it at least in the README as a note.

[octoprint_lock.log --> Log with both plugin enabled after the locking](https://github.com/OctoPrint/OctoPrint-CommandSplitter/files/4529761/octoprint_lock.log)
[Pin_0.3_2_Test.gcode.txt --> Original gcode](https://github.com/OctoPrint/OctoPrint-CommandSplitter/files/4529763/Pin_0.3_2_Test.gcode.txt)
[octoprint_plugindisabled.log --> Log with only PrusaSlicer no lock](https://github.com/OctoPrint/OctoPrint-CommandSplitter/files/4529825/octoprint_plugindisabled.log)
[Pin_0.3_2_Test.ReDownloaded.gcode.txt --> GCODE downloaded from Octoprint ](https://github.com/OctoPrint/OctoPrint-CommandSplitter/files/4529836/Pin_0.3_2_Test.ReDownloaded.gcode.txt)

With a diff you can note that there are some modification on first lines where some empty lines are removed. ( see also the screenshoot ).
![Screenshot 2020-04-24 at 17 29 13](https://user-images.githubusercontent.com/365884/80229813-423d2d80-8651-11ea-84f3-b69598f12e89.png)


```
$> diff Pin_0.3_2_Test.ReDownloaded.gcode.txt  Pin_0.3_2_Test.gcode.txt
20a21
>
21a23,24
>
>
38a42
>
217c221,222
< ;
---
> ;
>
223a229
>
229a236
>
```

**Comment by foosel** [comment]
Latest release has the line parser rewritten for performance reasons, and that seems to also have taken care of the whitespace shenanigans. Your test file shows no more differences after processing. Please test if 0.2.2 still causes issues for you.
