### ISSUE TITLE
Unable to upload gcode

### ISSUE THREAD

**Issue by Hypertoken** [OctoPrint/OctoPrint-CommandSplitter#3]
After fresh install of Octopi, update Octoprint to latest version. Installing CommandSplitter, you are unable to upload files via Web interface or "Watched" folder. Error is "Could not upload the file. Make sure that it is a readable, valid file with one of these extensions: .g, .gco, .gcode"

Environment: 
Windows 10 - Chrome v. 84.0.4147.89 - Simplify3D 
Raspberry Pi 4 2GB (also on Rpi 3B+) - Octopi 0.17.0

Steps to reproduce; 
Install Octopi 0.17
Update Octoprint to 1.4.0
Upload File (success)
Install CommandSplitter
Upload File (failed)

[octoprint.log](https://github.com/OctoPrint/OctoPrint-CommandSplitter/files/4978486/octoprint.log)

**Comment by ShohninDmitriy** [comment]
Same problem after updating to 0.2.2, version 0.2.1 works fine

**Comment by foosel** [comment]
Can either of you test if the problem persists with 1.4.1rc3 (maintenance release channel)?

**Comment by foosel** [comment]
0.2.3 should fix that. Was a Python 2 only issue which is why I couldn't immediately reproduce it.
